using TMPro;
using UnityEngine;
using UnityEngine.Localization.Settings;

public class LoreDetails : MonoBehaviour
{
    [SerializeField] private TMP_Text text;
    [SerializeField] public string[] collectibleIDs;

    private readonly string[] _fullLore =
    {
        "    In Greek mythology, Daedalus was an exceptionally skilled craftsman, an inventor, and a gifted architect. Many ancient creations and structures have been ascribed to him, prompting King Minos of Crete to seek him out for the construction of a place that could hold the accursed Minotaur. Thus, Daedalus designed the intricate Labyrinth, and—when banned from ever leaving the island—he invented a pair of wings to fly away from Crete. Daedalus's ingenuity made him a symbol of technical prowess and invention in ancient times, a form in which he persists as a symbol even in modern times.",
        "    The Labyrinth of Crete was a vast and complex maze designed by the master artisan Daedalus to imprison the Minotaur—a violent humanoid creature with the body of a man and the head of a bull. Its sprawling structure ensured that all those who entered it quickly lost their way and became trapped. It was built to house the Minotaur, whom the King Minos was told to spare, and it remained the creature's dwelling until it was slain. The Labyrinth of Crete as a symbol of an inescapable puzzle became so entrenched in our culture that it quickly became a regular noun used to describe any similar situation, real or metaphorical.",
        "    Crete is the largest and most populous of the Greek islands, located in the eastern part of the Mediterranean Sea. Located in a strategic location with access to particularly fertile soil, it quickly developed into a cultural and trading hub for ancient Greece. It has also been a site of profound importance in Greek mythology, witnessing events such as the birth of Zeus or the whole saga of the Labyrinth. Historically, it held the esteemed title of the capital of the Minoan civilization, whose art and culture were considered among the most impressive in ancient times. The ruins of its many palaces survive to the present day, giving us insight into the minds of the ancient masters and inspiring many artists for centuries after the fall of Crete itself.",

        "    After helping Theseus (a hero from Athens who has slain the Minotaur) escape the Labyrinth, Daedalus was punished by King Minos. The inventor and his son were imprisoned in a tall tower from which there was no escape. However, the inventiveness of Daedalus was proven to be unparalleled once again when, observing the birds flying free in the skies, he invented wings made from feathers and wax on which he and his son could escape.",
        "    King Minos is a recurring character in Greek mythology. While perhaps best known for commissioning Daedalus to construct the Labyrinth for the Minotaur, Minos was involved in most myths concerning Crete. Usually depicted as a ruthless figure, Minos used to be known as a formidable character for the ancient Greeks. Though his actions could be considered barbaric, the myths rarely paint him in negative colors, justifying his behavior with his absolute power in a way that can be dissonant for contemporary readers.",
        "    The Minotaur was a man-like monster born from the union of Queen Pasiphae and a bull. It was Poseidon's punishment for King Minos's reluctance to sacrifice the bull to the gods. After consulting an oracle, King Minos had the monster imprisoned in the Labyrinth and fed a diet of human sacrifices from Athens. Eventually, the Minotaur was slain by Theseus with the help of Ariadne and Daedalus, undermining Minos's pride.",

        "    The Flight of Icarus is the tragic conclusion of the Icarus and Daedalus's story in Greek mythology. After their imprisonment by King Minos, Daedalus designed and meticulously crafted two pairs of wings from wax and feathers with the hopes of escaping the island. The wings worked perfectly, but Icarus, enraptured by the freedom of flight, ignored his father's warnings and flew too close to the sun. The sun's heat melted the wax in his wings, and Icarus plummeted to his death in the sea. The tale is well known and often repeated as an example of the dangers of hubris.",
        "    Wings in Greek mythology were often a symbol of freedom, transcendence, and connection to divinity. Many winged creatures in mythology are mystic forces beyond humanity's control, such as the winged horse Pegaus, who carried lightning from heaven, or even harpies, who in early ancient Greece were depicted as wind spirits taking the form of beautiful and capricious women. Daedalus creating the wings for himself and his son was therefore the culmination of his craft, breaching the divine domain with human inventiveness and skill.",
        "    As one of the most famous moments in Greek mythology, the finale of the story of Icarus and Daedalus was immortalized in many pieces of art across the ages, from antiquity to modern times. It's a cautionary tale showing the terrible consequences of overambition and hubris, since Icarus caused his own demise by disregarding his father's advice. Another common interpretation is that Icarus and Daedalus broke natural boundaries by breaching the heavens and were punished for their pride.",

        "    Theseus was an ambitious hero of Athens. As the son of Aegeus, the king of Athens, he undertook a challenging journey known as the Six Labors before returning to the city of his father. However, he's most famous for volunteering to kill the Minotaur and end the human tribute Athens paid to Crete. With the help of Ariadne and Daedalus, he successfully completed that task and took his place in Athens as a great king whose legacy lived to the end of ancient Athens.",
        "    King Minos had two daughters. The elder of the two, called Ariadne, quickly fell in love with the young Theseus during his stay in Crete on his noble quest to slay the Minotaur. She secretly gave Theseus one end of a ball of thread, allowing him to easily escape the Labyrinth, and relayed to him advice from Daedalus, which proved to be crucial in finding the beast. Ariadne's thread has since become a symbol of guidance and problem-solving in difficult situations.",
        "    After the Minotaur was killed, Theseus took the young Athenians that were sent as a tribute, and together with Ariadne fled Crete to escape the wrath of King Minos. What happened to the group later has been the subject of much debate in antiquity, but one popular version says that when Theseus and the others fell asleep on the enchanted island of Naxos, he could not remember her upon waking and left her before returning to Athens. Regardless of the details, he comes back to Athens alone in all versions of the story, with the forgotten Ariadne being taken as a wife by the god Dionysus. In a different part of Greece, Daedalus returned to a quiet life in obscurity after mourning the death of his son.",

        "    W mitologii greckiej Dedal był niezwykle uzdolnionym rzemieślnikiem, wynalazcą i utalentowanym architektem. Wiele starożytnych wynalazków i budowli przypisywano właśnie jemu, co skłoniło króla Minosa z Krety do poszukiwania go w celu zbudowania miejsca, które mogłoby pomieścić przeklętego Minotaura. W ten sposób Dedal zaprojektował skomplikowany Labirynt, a gdy zakazano mu opuszczania wyspy, wynalazł parę skrzydeł, aby odlecieć z Krety. Pomysłowość Dedala uczyniła go symbolem technicznej biegłości i wynalazczości w starożytności, i w tej formie pozostaje on symbolem nawet w czasach współczesnych.",
        "    Labirynt na Krecie był rozległym i skomplikowanym labiryntem zaprojektowanym przez mistrza rzemiosła, Dedala, aby uwięzić Minotaura - brutalnego stwora o ludzkim ciele i głowie byka. Jego rozległa struktura sprawiała, że wszyscy, którzy do niego wchodzili, szybko tracili orientację i zostawali uwięzieni. Został zbudowany, aby pomieścić Minotaura, którego król Minos miał oszczędzić, i pozostawał siedzibą stwora aż do jego zabicia. Labirynt na Krecie jako symbol nierozwiązywalnej zagadki tak mocno zakorzenił się w naszej kulturze, że szybko stał się zwykłym rzeczownikiem używanym do opisywania wszelkich podobnych sytuacji, zarówno realnych, jak i metaforycznych.",
        "    Kreta jest największą i najbardziej zaludnioną z greckich wysp, położoną we wschodniej części Morza Śródziemnego. Znajdując się w strategicznym miejscu z dostępem do wyjątkowo żyznej gleby, szybko rozwinęła się w centrum kulturalne i handlowe starożytnej Grecji. Była również miejscem o głębokim znaczeniu w mitologii greckiej, będąc świadkiem takich wydarzeń jak narodziny Zeusa czy cała saga o Labiryncie. Historycznie pełniła zaszczytną rolę stolicy cywilizacji minojskiej, której sztuka i kultura były uważane za jedne z najbardziej imponujących w starożytności. Ruiny jej licznych pałaców przetrwały do dziś, dając nam wgląd w umysły starożytnych mistrzów i inspirując wielu artystów przez stulecia po upadku samej Krety.",

        "    Po pomocy Tezeuszowi (bohaterowi z Aten, który zabił Minotaura) w ucieczce z Labiryntu, Dedal został ukarany przez króla Minosa. Wynalazca i jego syn zostali uwięzieni w wysokiej wieży, z której nie było ucieczki. Jednak pomysłowość Dedala po raz kolejny okazała się niezrównana, gdy obserwując ptaki swobodnie latające po niebie, wynalazł skrzydła zrobione z piór i wosku, na których on i jego syn mogli uciec.",
        "    Król Minos jest postacią często pojawiającą się w mitologii greckiej. Choć być może najbardziej znany jest z tego, że zlecił Dedalowi zbudowanie Labiryntu dla Minotaura, Minos był zaangażowany w większość mitów dotyczących Krety. Zwykle przedstawiany jako bezwzględna postać, Minos był znany starożytnym Grekom jako groźny charakter. Chociaż jego czyny mogłyby być uznane za barbarzyńskie, mity rzadko przedstawiają go w negatywnym świetle, usprawiedliwiając jego zachowanie absolutną władzą w sposób, który może być dysonansem dla współczesnych czytelników.",
        "    Minotaur był potworem podobnym do człowieka, zrodzonym z związku królowej Pazyfae i byka. Był on karą Posejdona za niechęć króla Minosa do poświęcenia byka bogom. Po konsultacji z wyrocznią, król Minos uwięził potwora w Labiryncie i karmił go ludzkimi ofiarami z Aten. Ostatecznie Minotaur został zabity przez Tezeusza z pomocą Ariadny i Dedala, co podważyło dumę Minosa.",

        "    Lot Ikara to tragiczne zakończenie historii Ikara i Dedala w mitologii greckiej. Po uwięzieniu przez króla Minosa, Dedal zaprojektował i starannie wykonał dwie pary skrzydeł z wosku i piór, mając nadzieję na ucieczkę z wyspy. Skrzydła działały doskonale, ale Ikar, zachwycony wolnością lotu, zignorował ostrzeżenia ojca i poleciał zbyt blisko słońca. Ciepło słoneczne stopiło wosk w jego skrzydłach, a Ikar runął na śmierć do morza. Ta opowieść jest dobrze znana i często powtarzana jako przykład niebezpieczeństw płynących z hybris (pychy).",
        "    Skrzydła w mitologii greckiej były często symbolem wolności, transcendencji i związku z boskością. Wiele skrzydlatych stworzeń w mitologii to mistyczne siły pozostające poza kontrolą człowieka, takie jak skrzydlaty koń Pegaz, który przenosił błyskawice z nieba, czy nawet harpie, które we wczesnej starożytnej Grecji były przedstawiane jako duchy wiatru przybierające postać pięknych i kapryśnych kobiet. Stworzenie skrzydeł przez Dedala dla siebie i swojego syna było zatem kulminacją jego rzemiosła, naruszającą boską domenę ludzką pomysłowością i umiejętnościami.",
        "    Jako jeden z najbardziej znanych momentów w mitologii greckiej, finał historii Ikara i Dedala został uwieczniony w wielu dziełach sztuki na przestrzeni wieków, od starożytności po czasy współczesne. Jest to przestroga pokazująca straszliwe konsekwencje nadmiernej ambicji i pychy, ponieważ Ikar spowodował własną zgubę, lekceważąc rady ojca. Inna powszechna interpretacja mówi, że Ikar i Dedal przekroczyli naturalne granice, naruszając niebiosa, i zostali ukarani za swoją pychę.",

        "    Tezeusz był ambitnym bohaterem Aten. Jako syn Egeusza, króla Aten, podjął się trudnej podróży znanej jako Sześć Prac, zanim powrócił do miasta swego ojca. Jednak najbardziej znany jest z tego, że zgłosił się na ochotnika, by zabić Minotaura i położyć kres daninie z ludzi, którą Ateny płaciły Krecie. Z pomocą Ariadny i Dedala z powodzeniem wykonał to zadanie i zajął swoje miejsce w Atenach jako wielki król, którego spuścizna przetrwała do końca starożytnych Aten.",
        "    Król Minos miał dwie córki. Starsza z nich, zwana Ariadną, szybko zakochała się w młodym Tezeuszu podczas jego pobytu na Krecie w trakcie szlachetnej misji zabicia Minotaura. Potajemnie dała Tezeuszowi jeden koniec kłębka nici, umożliwiając mu łatwą ucieczkę z Labiryntu, i przekazała mu rady od Dedala, które okazały się kluczowe w odnalezieniu bestii. Nić Ariadny stała się od tego czasu symbolem przewodnictwa i rozwiązywania problemów w trudnych sytuacjach.",
        "    Po zabiciu Minotaura, Tezeusz zabrał młodych Ateńczyków, którzy zostali wysłani jako danina, i razem z Ariadną uciekli z Krety, aby uniknąć gniewu króla Minosa. To, co stało się z grupą później, było przedmiotem wielu dyskusji w starożytności, ale jedna z popularnych wersji mówi, że kiedy Tezeusz i inni zasnęli na zaczarowanej wyspie Naksos, po przebudzeniu nie mógł jej sobie przypomnieć i opuścił ją przed powrotem do Aten. Niezależnie od szczegółów, we wszystkich wersjach historii wraca on do Aten sam, a zapomniana Ariadna zostaje poślubiona przez boga Dionizosa. W innej części Grecji Dedal, po opłakaniu śmierci syna, powrócił do cichego życia w zapomnieniu."
    };

    public void SetLoreDetails(int details)
    {
        var locale = LocalizationSettings.SelectedLocale;
        text.text = locale.Identifier.Code == "pl" ? _fullLore[details + 12] : _fullLore[details];
    }

    public void ClearAllLoreProgress()
    {
        foreach (var collectible in collectibleIDs) PlayerPrefs.SetInt(collectible, 0);
    }
}